import { MaterialCommunityIcons } from '@expo/vector-icons';


export const logoOptions = [
    { label: 'Randonnée', value: 'hiking', icon: () => <MaterialCommunityIcons name="hiking" size={24} color="#510D0A" /> },
    { label: 'Cuisine', value: 'chef-hat', icon: () => <MaterialCommunityIcons name="chef-hat" size={24} color="#510D0A" /> },
    { label: 'Méditation', value: 'meditation', icon: () => <MaterialCommunityIcons name="meditation" size={24} color="#510D0A" /> },
    { label: 'Peinture', value: 'brush', icon: () => <MaterialCommunityIcons name="brush" size={24} color="#510D0A" /> },
    { label: 'Musique', value: 'music-note', icon: () => <MaterialCommunityIcons name="music-note" size={24} color="#510D0A" /> },
    { label: 'Sport', value: 'soccer', icon: () => <MaterialCommunityIcons name="soccer" size={24} color="#510D0A" /> },
    { label: 'Voyage', value: 'airplane', icon: () => <MaterialCommunityIcons name="airplane" size={24} color="#510D0A" /> },
    { label: 'Technologie', value: 'laptop', icon: () => <MaterialCommunityIcons name="laptop" size={24} color="#510D0A" /> },
    { label: 'Santé', value: 'heart-pulse', icon: () => <MaterialCommunityIcons name="heart-pulse" size={24} color="#510D0A" /> },
    { label: 'Lecture', value: 'book-open-variant', icon: () => <MaterialCommunityIcons name="book-open-variant" size={24} color="#510D0A" /> },
    { label: 'Éducation', value: 'school', icon: () => <MaterialCommunityIcons name="school" size={24} color="#510D0A" /> },
    { label: 'Environnement', value: 'tree', icon: () => <MaterialCommunityIcons name="tree" size={24} color="#510D0A" /> },
    { label: 'Art', value: 'palette', icon: () => <MaterialCommunityIcons name="palette" size={24} color="#510D0A" /> },
    { label: 'Jeux', value: 'gamepad-variant', icon: () => <MaterialCommunityIcons name="gamepad-variant" size={24} color="#510D0A" /> },
    { label: 'Cinéma', value: 'movie-open', icon: () => <MaterialCommunityIcons name="movie-open" size={24} color="#510D0A" /> },
    { label: 'Fitness', value: 'dumbbell', icon: () => <MaterialCommunityIcons name="dumbbell" size={24} color="#510D0A" /> },
    { label: 'Danse', value: 'dance-ballroom', icon: () => <MaterialCommunityIcons name="dance-ballroom" size={24} color="#510D0A" /> },
    { label: 'Photographie', value: 'camera', icon: () => <MaterialCommunityIcons name="camera" size={24} color="#510D0A" /> },
    { label: 'Jardinage', value: 'flower', icon: () => <MaterialCommunityIcons name="flower" size={24} color="#510D0A" /> },
    { label: 'Astronomie', value: 'telescope', icon: () => <MaterialCommunityIcons name="telescope" size={24} color="#510D0A" /> },
    { label: 'Vélo', value: 'bike', icon: () => <MaterialCommunityIcons name="bike" size={24} color="#510D0A" /> },
    { label: 'Théâtre', value: 'drama-masks', icon: () => <MaterialCommunityIcons name="drama-masks" size={24} color="#510D0A" /> },
    { label: 'Mode', value: 'tshirt-crew', icon: () => <MaterialCommunityIcons name="tshirt-crew" size={24} color="#510D0A" /> },
    { label: 'Programmation', value: 'code-tags', icon: () => <MaterialCommunityIcons name="code-tags" size={24} color="#510D0A" /> },
    { label: 'Médecine', value: 'stethoscope', icon: () => <MaterialCommunityIcons name="stethoscope" size={24} color="#510D0A" /> },
    { label: 'Sciences', value: 'atom', icon: () => <MaterialCommunityIcons name="atom" size={24} color="#510D0A" /> },
    { label: 'Yoga', value: 'yoga', icon: () => <MaterialCommunityIcons name="yoga" size={24} color="#510D0A" /> },
    { label: 'Cuisine Rapide', value: 'food-fork-drink', icon: () => <MaterialCommunityIcons name="food-fork-drink" size={24} color="#510D0A" /> },
    { label: 'Randonnée', value: 'map-marker-path', icon: () => <MaterialCommunityIcons name="map-marker-path" size={24} color="#510D0A" /> },
    { label: 'Couture', value: 'needle', icon: () => <MaterialCommunityIcons name="needle" size={24} color="#510D0A" /> },
    { label: 'Camping', value: 'tent', icon: () => <MaterialCommunityIcons name="tent" size={24} color="#510D0A" /> },
    { label: 'Course', value: 'run', icon: () => <MaterialCommunityIcons name="run" size={24} color="#510D0A" /> },
    { label: 'Architecture', value: 'office-building', icon: () => <MaterialCommunityIcons name="office-building" size={24} color="#510D0A" /> },
    { label: 'Animaux', value: 'paw', icon: () => <MaterialCommunityIcons name="paw" size={24} color="#510D0A" /> },
    { label: 'Pêche', value: 'fish', icon: () => <MaterialCommunityIcons name="fish" size={24} color="#510D0A" /> },
    { label: 'Nature', value: 'forest', icon: () => <MaterialCommunityIcons name="forest" size={24} color="#510D0A" /> },
  ];
  